name: CI/CD (New)

on:
  push:
    branches:
      - 'master'

jobs:  
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven and test
        run: mvn --batch-mode --update-snapshots verify
  
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Push with Maven
        run:  ./mvnw install -Dmaven.test.skip -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ secrets.DOCKERHUB_USERNAME }} -Dquarkus.container-image.password=${{ secrets.DOCKERHUB_TOKEN }}
